### ISSUE TITLE
支付完成微信通知点击不进入订单详细页面的关题

### ISSUE THREAD

**Issue by leadroy** [froger-me/woo-wechatpay#10]
通过配置微信WeChat Order Notification Template ID可以让用户收到订单通知，这个功能很强大很好用。
可能否实现在用户点击这个通知时直接跳转到订单详细页，更在好像只能到达订单清单页。
我不清楚是我配置问题还是插件本身就是这样实现的。

**Comment by froger-me** [comment]
Hi @leadroy !

The destination URL is the list of orders by default.
It can be changed the way you need with the `woo_wechatpay_templated_message_url` filter (added to theme functions.php or a custom plugin - replace `your_prefix` with a string of your choice):

```php
add_filter( 'woo_wechatpay_templated_message_url', 'your_prefix_woo_wechatpay_templated_message_url', 10, 2 );
function your_prefix_woo_wechatpay_templated_message_url( $url, $order ) {

  return $order->get_view_order_url();
}
```

**Comment by leadroy** [comment]
非常感谢！相信这个插件会越来越好。

**Comment by leadroy** [comment]
万分感谢！再次感谢您开发这么好用的插件。中国很多付费插件都没你开发的这个好用。

**Comment by froger-me** [comment]
Thanks for the praise!
If you'd like to support my work, please feel free to send a donation by WeChat 红包🧧!
