### ISSUE TITLE
send msg to payment_result['openid']

### ISSUE THREAD

**Issue by sleepm** [froger-me/woo-wechatpay#13]
if A has an order, B scan qrcode to pay
in function send_templated_message()
$openid = $payment_result['openid'];
so B get the msg and order info

**Comment by froger-me** [comment]
Hi!
What is the issue? B fulfilled the transaction, therefore B receives the confirmation templated message - this is in line with Tencent guidelines regarding templated messages (as in: send template messages to a WeChat account only in response to actions initiated by said WeChat account).

If you want to change this behavior, you can use the `woo_wechatpay_templated_message` filter for that.

**Comment by sleepm** [comment]
thansk to reply
