### ISSUE TITLE
No qrcode

### ISSUE THREAD

**Issue by ghost** [froger-me/woo-wechatpay#3]
RT

![wx20190105-233927](https://user-images.githubusercontent.com/19859110/50726391-594bc980-1147-11e9-8b6c-bef791e02777.png)

**Comment by froger-me** [comment]
> Woo WeChatPay has been tested with the latest version of WordPress and WooCommerce – in case of issue, please ensure you are able to reproduce it with a default installation of WordPress, WooCommerce plugin, and Storefront theme and any of the aforementioned supported plugins if used before reporting a bug.

Please let me know the steps to reproduce the issue or any other useful information. The feature is currently working on my own test website.
