### ISSUE TITLE
The order has failed. Reason: 签名错误

### ISSUE THREAD

**Issue by MarcusCaeruleus** [froger-me/woo-wechatpay#4]
@froger-me Sorry to keep pestering you with questions. We have the WeChat login and force follow working without issue, but can't seem to get payments working in the WeChatPay plugin. We are getting the following signature error each time a payment is attempted. 

Please scan the QR code with WeChat to finish the payment.
Error generating the payment QR code. If the problem persists, please contact our services.
The order has failed. Reason: 签名错误

The certificate files are in an accessible directory and all other settings, to the bets of my knowledge, filled in with the appropriate details from the WeChat merchant backend. 

Any thoughts on where I may be missing a step?

**Comment by froger-me** [comment]
Hi @MarcusCaeruleus !
Payment is a bit of a pain to configure in the WeChat backend. Did you enter all the JSAPI Payment Authorization URLs and the QR Payment callback URL in the backend?

I assume the issue you are describing is happening in classic browsers and not in WeChat browser, correct?

**Comment by MarcusCaeruleus** [comment]
Your not wrong on it being a pain. All the URLs have been entered and we are experiencing the same issue in both the WeChat Browser and traditional browsers.

**Comment by froger-me** [comment]
A few questions to explore:

1.  Are you using a cache plugin on the website? (and is there any change if you flush the cache or deactivate the cache plugin)
2. Do you mean you are getting the QR code page in WeChat mobile browser? (it should not be a QR payment, but native payment)
3. Could you please flush the WordPress permalinks?

**Comment by MarcusCaeruleus** [comment]
@froger-me 
1) I'm using Autoptimise, but deactivated it with same result. 
2) No QR code appears in normal browsers or H5
3) Permalinks flushed with same result

I've attached an image of the problem within the H5 browser for your reference.

![img_2903](https://user-images.githubusercontent.com/45415154/51663082-b1f8de80-1ff0-11e9-9bf7-0b9af3edfa81.jpeg)

**Comment by froger-me** [comment]
Would you mind communicating with me in private and send me the link to your website?

**Comment by MarcusCaeruleus** [comment]
@froger-me Thanks for you help on this. It seems the issue was human error. What I thought was the Merchant Key was actually something else. For anyone else looking to find the Merchant key, it is hidden (if you don't read Chinese well) behind the green button.

![341548388508_ pic](https://user-images.githubusercontent.com/45415154/51728001-81c14680-20a9-11e9-9507-4573cf3bbe2b.jpg)
