### ISSUE TITLE
No settings available with Wordpress 5.2.2 WooCommerce 3.6.5

### ISSUE THREAD

**Issue by jazzi** [froger-me/woo-wechatpay#6]
After activated, can not find WeChat Pay on the list of WooCommerce > Settings > Payments >

Thus no way to configure this gateway.

Is this a compatible problem?

Wordpress 5.2.2
WooCommerce 3.6.5

**Comment by froger-me** [comment]
Hello @jazzi 
Could you confirm you have the WP Weixin core plugin activated and configured properly alongside the Woo WeChatPay plugin?
I tested just now with the latest version of WordPress, WooCommerce and WooCommerce Admin and the gateway is visible.

**Comment by jazzi** [comment]
My mistake, didn't see the following requirement:

`WP Weixin installed, activated, enabled and properly configured.`

After above core plugin installed, everything goes fine.
Thank you @froger-me
