### ISSUE TITLE
Any sandbox for testing?

### ISSUE THREAD

**Issue by chuenlum** [froger-me/woo-wechatpay#7]
Hi, I have configured the plugin and it generated a QR code. Unfortunately, I'm not sure how to test it without paying actual real money. Is there some way we can test WeChat pay like how we have Stripe / PayPal sandbox?

**Comment by froger-me** [comment]
Hi @chuenlum 
I have not used not integrated any sandbox for payment - instead I developed and tested with transfers of 0.01 RMB.
