### ISSUE TITLE
Version 1.3.5 mobile browser H5 payment not calling WeChat App

### ISSUE THREAD

**Issue by ghost** [froger-me/woo-wechatpay#8]
Hi Alexandre,

I just updated both WP Weixin, Woo WeChat Pay plug-ins to latest version 1.3.5.
Step 1: they were both deactivated.
Step 2: FTP deleted both plug-in folders (WordPress site is not accessible from China host...)
Step 3: FTP uploaded both version 1.3.5 plug-in folders
Step 4: activated both plug-ins

However, H5 payment in both mobile Safari / mobile Chrome browsers is still not working (showing a payment bar code instead of calling WeChat App to make payment).

The WeChat Pay Merchant Account has enabled H5 payment feature at account level. Has the right domain authorization within WeChat Pay.

A sample product (virtual product) is this:
https://www.elegment.cn/product/book/

Do you know what is the reasoning? I have attached  screen captures below.

Thanks in advance.

Xing Gao
![0](https://user-images.githubusercontent.com/59902638/73146942-af551d00-407a-11ea-8699-475334db8724.jpg)
![1](https://user-images.githubusercontent.com/59902638/73146944-afedb380-407a-11ea-8a7b-83a8c6d2d078.jpg)
![2](https://user-images.githubusercontent.com/59902638/73146947-afedb380-407a-11ea-962d-ccfb91aab9bb.jpg)
![3](https://user-images.githubusercontent.com/59902638/73146948-b11ee080-407a-11ea-865e-1bc366514392.jpg)

**Comment by froger-me** [comment]
Hello @xing-gao 

Did you activate the H5 support in the payment gateway setting? https://www.elegment.cn/wp-admin/admin.php?page=wc-settings&tab=checkout&section=wechatpay > "H5 payment in mobile web browsers" checkbox

This setting is in place to make sure the plugin would still work with a QR code by default in all browsers in case the admin did not enable H5 payment in the WeChat backend.

**Comment by ghost** [comment]
Yes, this is it! Thanks Alexandre
